version: '3'

volumes:
  kittygram_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_data:/var/lib/postgresql/data
  backend:
    image: akatsukisanya/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    image: akatsukisanya/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: akatsukisanya/kittygram_gateway
    ports:
      - 9000:80
    depends_on:
      - backend
    volumes:
      - static:/staticfiles/
